version: '3.8'

services:
  # Prefect server with SQLite
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect

  # FastAPI application
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PHOTOROOM_API_KEY: ${PHOTOROOM_API_KEY}
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      - prefect-server
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  prefect_data:
