services:
  # Prefect server with SQLite
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect

  # MinIO for object storage (S3 compatible)
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # FastAPI application
  fastapi-app:
    build: ./app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override some env vars specific to the docker environment
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      - prefect-server
      - minio
    volumes:
      - .:/app

volumes:
  prefect_data:
  minio_data:
