services:
  # Prefect server with SQLite
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    environment:
      # For internal service communication
      PREFECT_API_URL: http://prefect-server:4200/api
      # For browser UI access
      PREFECT_UI_API_URL: http://localhost:4200/api
    ports:
      - "4200:4200"
    networks:
      - prefect-network

  # Prefect worker for processing tasks
  prefect-worker:
    build:
      context: ./workflows
      dockerfile: Dockerfile.worker
      args:
        PREFECT_API_URL: http://prefect-server:4200/api
        POOL_NAME: test-pool
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    env_file:
      - .env
    depends_on:
      - prefect-server
      - minio
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prefect-network

  # MinIO for object storage (S3 compatible)
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - prefect-network

  # FastAPI application
  fastapi-app:
    build: ./app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override some env vars specific to the docker environment
      PREFECT_API_URL: http://prefect-server:4200/api
    # depends_on:
    #   - prefect-server
    #   - minio
    volumes:
      - .:/app
    networks:
      - prefect-network

volumes:
  prefect_data:
  minio_data:

networks:
  prefect-network:
    driver: bridge