services:
  # Prefect server with SQLite
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    environment:
      # For internal service communication
      PREFECT_API_URL: http://prefect-server:4200/api
      # For browser UI access
      PREFECT_UI_API_URL: http://localhost:4200/api
      PREFECT_RESULTS_PERSIST_BY_DEFAULT: true
    ports:
      - "4200:4200"
    networks:
      - prefect-network
    volumes:
      - prefect_data:/data
      - /tmp/prefect-results:/tmp/prefect-results

  # Prefect worker for processing tasks
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        PREFECT_API_URL: http://prefect-server:4200/api
        POOL_NAME: test-pool
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      MINIO_ENDPOINT: http://minio:9000
      PREFECT_RESULTS_PERSIST_BY_DEFAULT: true
      PREFECT_LOCAL_STORAGE_PATH: /tmp/prefect-results
    depends_on:
      - prefect-server
      - minio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/prefect-results:/tmp/prefect-results
    networks:
      - prefect-network

  # MinIO for object storage (S3 compatible)
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - prefect-network

  # FastAPI application
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override some env vars specific to the docker environment
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /tmp/prefect-results
    depends_on:
      - prefect-server
      - minio
    networks:
      - prefect-network
    volumes:
      - /tmp/prefect-results:/tmp/prefect-results

volumes:
  prefect_data:
  minio_data:

networks:
  prefect-network:
    driver: bridge